name: Publish Bleed Container

on:
  push:
    branches: ['main']
    paths-ignore:
      - '.development/**'
      - '.husky/**'
      - 'kustomize/**'
      - '.vscode/**'
      - 'cypress/**'

concurrency:
  group: publish-from-main
  cancel-in-progress: true

jobs:
  publish-bleed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up emulation
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/leemartin77/moodie:bleed
            ghcr.io/leemartin77/moodie:${{ github.sha }}
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-version:
    needs: publish-bleed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: Set new version
        run: yq e -i '.spec.template.spec.containers[0].image = "ghcr.io/leemartin77/moodie:${{ github.sha }}"' kustomize/deployment.yml
      - name: Commit and Push version
        run: |
          git config --global user.name 'Lee Martin[Automated]'
          git config --global user.email 'leemartin77@users.noreply.github.com'
          git commit -am "New Moodie Version"
          git push
